# Generated by Django 5.1.4 on 2024-12-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formhandling', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
