# Generated by Django 5.1.4 on 2024-12-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formhandling', '0003_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
